<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_ritzyImageHelper  = $this->helper('Arsal\CatalogParallax\Helper\Data');
$_category  = $block->getCurrentCategory();
$_imgHtml   = '';
if ($_imgUrl = $_ritzyImageHelper->getParallaxImageUrl($_category)) {
    $_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    /* @escapeNotVerified */ echo $_imgHtml;
}
?>
